ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS prenom TEXT,
  ADD COLUMN IF NOT EXISTS fonction TEXT,
  ADD COLUMN IF NOT EXISTS telephone TEXT,
  ADD COLUMN IF NOT EXISTS mail TEXT,
  ADD COLUMN IF NOT EXISTS comptabilite TEXT;
